version: '3.9'

services:
  app:
    container_name: nodejs-auth-service-sample-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: always

  postgres:
    image: postgres:latest
    container_name: local-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: localdb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:latest
    container_name: local_redis
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: always

volumes:
  pgdata:
  redisdata:
